import Link from "next/link";
import {ArticleLayout, ArticleSection, CheckList, InfoHero, PageCTA} from "@/app/components/InfoPage";

export default function AdvisorAgreementPage() {
  return <main className="min-h-screen">
    <InfoHero eyebrow="Advisor standards" title="Advisor Acceptable Use Policy" description="The professional, service-delivery and payment standards that apply to anyone offering sessions through Workspherepulse." action={{label:"Apply as an advisor",href:"/program/onboard"}} />
    <ArticleLayout label="Workspherepulse advisors" aside={<div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-[0.16em] text-slate-400">Advisor resources</p><div className="mt-4 space-y-3 text-sm font-bold text-[#59604c]"><Link className="block" href="/seller-faq">Advisor FAQ →</Link><Link className="block" href="/cancellations-refunds">Refund policy →</Link><Link className="block" href="/privacy">Privacy policy →</Link></div></div>}>
      <ArticleSection number="01" title="Purpose"><p>This policy sets the standards advisors must follow when offering professional guidance through Workspherepulse. Advisors must also comply with applicable law, payment-provider rules and the other platform terms.</p></ArticleSection>
      <ArticleSection number="02" title="Permitted services"><p>Advisors may offer lawful, accurately described professional consultations that match their disclosed expertise and qualifications.</p><CheckList items={["Provide clear and accurate profile information.","Offer only services you are qualified and legally permitted to provide.","Deliver confirmed sessions professionally and on time.","Keep customer and session information confidential."]}/></ArticleSection>
      <ArticleSection number="03" title="Prohibited services and conduct"><p>Advisors may not:</p><CheckList items={["Offer unlawful, deceptive, discriminatory, explicit or infringing services.","Provide regulated services without the required licence or authorisation.","Promote gambling, high-risk financial schemes or guaranteed outcomes.","Misrepresent identity, qualifications, certifications or experience.","Harass users or engage in threatening or unsafe conduct."]}/></ArticleSection>
      <ArticleSection number="04" title="Payment integrity"><CheckList items={["Do not request or accept off-platform payment for Workspherepulse bookings.","Do not manipulate refunds, disputes, attendance or chargebacks.","Do not use stolen payment information or facilitate transaction laundering.","Complete payment-provider identity and payout onboarding truthfully."]}/></ArticleSection>
      <ArticleSection number="05" title="Service delivery"><CheckList items={["Maintain accurate availability and attend scheduled meetings.","Deliver the session described by the profile and booking.","Respond to booking-related communication within a reasonable time.","Cooperate with legitimate dispute and attendance reviews."]}/><p>Failure to deliver may lead to a refund, payout hold, account review or suspension.</p></ArticleSection>
      <ArticleSection number="06" title="Cancellations, refunds and disputes"><p>Advisors must follow the current cancellation and refund policy. Workspherepulse may pause, withhold or reverse payouts where necessary to handle non-delivery, refunds, disputes, chargebacks, fraud or policy violations.</p></ArticleSection>
      <ArticleSection number="07" title="Privacy and data"><CheckList items={["Use customer information only to deliver the booked service.","Do not store payment credentials.","Do not disclose private session or account information without lawful authority.","Follow applicable data-protection requirements."]}/></ArticleSection>
      <ArticleSection number="08" title="Independent provider status"><p>Advisors operate as independent service providers. They are responsible for their own taxes, licences, insurance and professional obligations. Approval to use Workspherepulse does not create an employment relationship.</p></ArticleSection>
      <ArticleSection number="09" title="Monitoring and enforcement"><p>Workspherepulse may review complaints, booking and payment activity, meeting records, and information relevant to platform safety or policy compliance. Violations may result in warnings, payout restrictions, suspension, termination or reporting to appropriate authorities.</p></ArticleSection>
      <ArticleSection number="10" title="Changes and contact"><p>This policy may be updated as the platform, laws or payment rules change. Continued advisor use after an update constitutes acceptance where permitted by law.</p><p><strong>Workspherepulse LLC</strong><br/>3112 Centerville Rd, Greenville, DE 19807, USA<br/><a href="mailto:admin@workspherepulse.com" className="font-bold text-[#59604c]">admin@workspherepulse.com</a></p></ArticleSection>
    </ArticleLayout>
    <PageCTA title="Build your advisor profile." description="Share your expertise, set a rate and availability, then submit your application for Workspherepulse review." primary={{label:"Apply as an advisor",href:"/program/onboard"}} secondary={{label:"Read advisor FAQ",href:"/seller-faq"}} />
  </main>;
}
