import Link from "next/link";
import {ArticleLayout, ArticleSection, CheckList, InfoHero, PageCTA} from "@/app/components/InfoPage";

export default function CancellationsRefundsPage() {
  return <main className="min-h-screen">
    <InfoHero eyebrow="Bookings and payments" title="Cancellations and Refunds Policy" description="How Workspherepulse reviews cancellations, no-shows, failed sessions, disputes and approved refunds." action={{label:"Get booking support",href:"/contact"}} />
    <ArticleLayout label="Paid advisor sessions" aside={<div className="rounded-3xl border border-amber-200 bg-amber-50 p-6"><p className="text-xs font-bold uppercase tracking-[0.16em] text-amber-700">Before contacting us</p><p className="mt-3 text-sm leading-6 text-amber-900">Have your Workspherepulse username, advisor name and scheduled date ready so we can locate the booking.</p></div>}>
      <ArticleSection number="01" title="Booking confirmation"><CheckList items={["Sessions must be booked and paid for through Workspherepulse.","A confirmed booking shows the scheduled date, time, advisor and session duration.","Payment is processed securely by the platform payment provider."]}/></ArticleSection>
      <ArticleSection number="02" title="Attendance verification"><p>Workspherepulse uses meeting records and Zoom webhook events to help verify whether a session started, ended and had sufficient participation. We use this information alongside booking and support records when reviewing a delivery issue.</p></ArticleSection>
      <ArticleSection number="03" title="Advisor no-shows or delivery failures"><p>If the advisor does not attend, or a confirmed platform problem prevents delivery, contact support promptly.</p><CheckList items={["We review the booking and available meeting records.","A confirmed non-delivery may qualify for a full refund or rescheduling.","Repeated advisor no-shows may lead to payout restrictions or account suspension."]}/></ArticleSection>
      <ArticleSection number="04" title="Customer cancellations and no-shows"><p>Cancellation eligibility depends on when the request is made and the booking status. A late cancellation or customer no-show may not qualify for a refund. Where attendance is disputed, available meeting records will be reviewed.</p></ArticleSection>
      <ArticleSection number="05" title="Dispute review"><p>When a dispute is opened, payout release may be paused while we review:</p><CheckList items={["Payment and booking records.","Meeting start, end and participation information.","The reason supplied by the customer or advisor.","Relevant support communications."]}/><p>Most disputes are reviewed within 48–72 hours. Urgent same-day meeting-access issues are prioritised.</p></ArticleSection>
      <ArticleSection number="06" title="Refunds and payout controls"><CheckList items={["Approved refunds are sent to the original payment method.","Payment-provider processing time may affect when funds appear.","Advisor payout may remain on hold until session completion is verified.","A completed transfer may be reversed where required for an approved refund or dispute."]}/></ArticleSection>
      <ArticleSection number="07" title="What may not qualify"><CheckList items={["A completed session where both parties attended and the service was delivered.","A complaint unrelated to delivery or outside the applicable request period.","A customer no-show or late cancellation that is not covered by the booking terms.","A request involving fraud, abuse or inaccurate information."]}/></ArticleSection>
      <ArticleSection number="08" title="Requesting support"><p>Email <a href="mailto:admin@workspherepulse.com" className="font-bold text-[#59604c]">admin@workspherepulse.com</a> or use the Contact page. A refund request pauses automatic release where supported, but it does not guarantee approval.</p><Link href="/contact" className="font-bold text-[#59604c]">Open support options →</Link></ArticleSection>
    </ArticleLayout>
    <PageCTA title="Something went wrong with a session?" description="Contact support with the booking details and we will review the available payment and attendance records." primary={{label:"Contact support",href:"/contact"}} secondary={{label:"View service guarantee",href:"/service-guarantee"}} />
  </main>;
}
