import Link from "next/link";
import {ClockIcon, ShieldCheckIcon, VideoCameraIcon} from "@heroicons/react/24/outline";
import {ArticleLayout, ArticleSection, CheckList, InfoHero, PageCTA} from "@/app/components/InfoPage";

export default function ServiceGuaranteePage() {
  return <main className="min-h-screen">
    <InfoHero eyebrow="Our commitment" title="Service delivery you can understand and trust." description="How Workspherepulse confirms sessions, supports users and responds when a booked service cannot be delivered as expected." action={{label:"Contact support",href:"/contact"}} />
    <section className="border-b border-slate-200 bg-white"><div className="mx-auto grid max-w-6xl gap-px bg-slate-200 px-6 sm:grid-cols-3">{[{icon:ShieldCheckIcon,title:"Approved advisors",text:"Applications are reviewed before booking access."},{icon:VideoCameraIcon,title:"Verified sessions",text:"Meeting activity helps confirm delivery."},{icon:ClockIcon,title:"Responsive support",text:"Most requests receive a reply within 24–48 hours."}].map(item => <div key={item.title} className="bg-white px-6 py-8"><item.icon className="h-7 w-7 text-[#69705a]"/><h2 className="mt-4 font-bold text-slate-950">{item.title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{item.text}</p></div>)}</div></section>
    <ArticleLayout label="Customers and advisors">
      <ArticleSection number="01" title="Service delivery guarantee"><p>Booked consultations are scheduled in advance and conducted digitally through the meeting details shown in your account.</p><p>If a session cannot be delivered because of a platform issue or advisor unavailability, we will review the booking and may:</p><CheckList items={["Offer a rescheduled session at no additional cost.","Provide a full refund to the original payment method when appropriate."]}/><p className="rounded-2xl bg-amber-50 p-4 text-sm text-amber-900"><strong>Scope:</strong> Workspherepulse provides non-clinical workplace wellbeing and professional-development guidance.</p></ArticleSection>
      <ArticleSection number="02" title="Customer support"><p>Support is available for account access, bookings, payments, meetings and advisor applications.</p><CheckList items={[<>Email <a className="font-bold text-[#59604c]" href="mailto:admin@workspherepulse.com">admin@workspherepulse.com</a>.</>,"Use your booking dashboard to review session details.","Include your username and booking date when contacting us about a session."]}/><p>Most requests receive a response within 24–48 hours. Urgent same-day meeting issues are prioritised.</p></ArticleSection>
      <ArticleSection number="03" title="Cancellations and refunds"><p>Eligibility depends on the booking status, timing, attendance information and reason for the request.</p><CheckList items={["A session not delivered because of a confirmed platform or advisor issue may qualify for a refund.","Approved refunds return to the original payment method.","No-shows or late cancellations may not qualify for a refund."]}/><Link href="/cancellations-refunds" className="inline-flex font-bold text-[#59604c]">Read the full cancellations and refunds policy →</Link></ArticleSection>
      <ArticleSection number="04" title="How sessions work"><p>Workspherepulse offers paid one-to-one sessions for workplace wellbeing, communication, stress management and professional growth. Approved human advisors provide scheduled guidance, while the AI advisor offers separate timed sessions.</p><p>Session access, payment state and meeting details remain connected to your Workspherepulse account.</p></ArticleSection>
    </ArticleLayout>
    <PageCTA title="Need help with a booked session?" description="Send our team the username and scheduled date so we can review the correct booking." primary={{label:"Contact support",href:"/contact"}} secondary={{label:"View appointments",href:"/program/appointments"}} />
  </main>;
}
