import {ArticleLayout, ArticleSection, CheckList, InfoHero} from "@/app/components/InfoPage";

export default function PrivacyPage() {
  return <main className="min-h-screen">
    <InfoHero eyebrow="Privacy" title="How Workspherepulse handles your information." description="A clear overview of the information we collect, why we use it and the choices available to you." />
    <ArticleLayout label="Website, app and community users">
      <ArticleSection number="01" title="Information we collect"><p>We collect information you provide and information generated when you use Workspherepulse.</p><CheckList items={["Account and contact information, such as name, username and email.","Advisor profile, expertise, availability and onboarding information.","Booking, session, payment status and service history.","Messages and support communications.","Device, security and usage information needed to operate and protect the services."]}/><p>Payment-card details are handled by the payment provider and are not stored directly by Workspherepulse.</p></ArticleSection>
      <ArticleSection number="02" title="How we use information"><CheckList items={["Create and secure accounts.","Arrange sessions and display booking details.","Process payments, refunds and advisor payouts.","Verify service delivery and resolve disputes.","Provide support and service notifications.","Prevent fraud, enforce policies and meet legal obligations.","Improve the reliability and usability of Workspherepulse."]}/></ArticleSection>
      <ArticleSection number="03" title="When information is shared"><p>We do not sell personal information. We may share the information necessary to operate the platform with advisors involved in a booking, payment and meeting providers, hosting and communication services, professional advisers, or authorities where required by law.</p></ArticleSection>
      <ArticleSection number="04" title="Data security and retention"><p>We use administrative, technical and organisational safeguards designed to protect information. No internet system can guarantee absolute security. We retain information for as long as needed to provide services, resolve disputes, meet financial and legal requirements, and protect the platform.</p></ArticleSection>
      <ArticleSection number="05" title="Your choices and rights"><p>Depending on your location, you may have rights to access, correct, delete, restrict or receive a copy of personal information, and to object to certain uses.</p><p>Send a request from your registered email address to <a href="mailto:admin@workspherepulse.com" className="font-bold text-[#59604c]">admin@workspherepulse.com</a>. We may need to verify your identity.</p></ArticleSection>
      <ArticleSection number="06" title="Cookies and similar technologies"><p>The website may use cookies or local storage required for account sessions, security, preferences and service measurement. Browser controls can limit optional storage, but disabling essential storage may prevent sign-in or other features from working.</p></ArticleSection>
      <ArticleSection number="07" title="Children"><p>Workspherepulse is intended for adults and is not directed to anyone under 18. We do not knowingly collect personal information from children.</p></ArticleSection>
      <ArticleSection number="08" title="International services"><p>Workspherepulse may use providers and infrastructure in countries different from your own. Where required, we use appropriate measures for international data transfers.</p></ArticleSection>
      <ArticleSection number="09" title="Changes and contact"><p>We may update this policy as services and legal requirements change. The current version will remain available on this page.</p><p><strong>Workspherepulse LLC</strong><br/>3112 Centerville Rd, Greenville, DE 19807, USA<br/><a href="mailto:admin@workspherepulse.com" className="font-bold text-[#59604c]">admin@workspherepulse.com</a></p></ArticleSection>
    </ArticleLayout>
  </main>;
}
